[package]
name = "picoo-windows-vcam-source"
description = "Windows Media Foundation virtual camera source implemented in Rust"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "picoo_virtual_camera_source"
crate-type = ["cdylib", "rlib"]

[dependencies]
picoo-frame-hub.workspace = true

[target.'cfg(windows)'.dependencies]
windows-core = "0.62.2"
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_Media_KernelStreaming",
    "Win32_Media_MediaFoundation",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Variant",
] }

[build-dependencies]
winresource = "0.1.31"
